### ISSUE TITLE
Wrong redirects after renaming app on Heroku

### ISSUE THREAD

**Issue by aledpardo** [tbgse/opensurvey#10]
Trying to log in with GitHub is redirecting to old app url:

Found this messages on browser log:

1
https://agile-citadel-84570.herokuapp.com/login/github?code=13d7ae4e2ce1e79cc2c5 
Failed to load resource: the server responded with a status of 404 (Not Found)

2
https://opensurvey.herokuapp.com/login/github/test?code=13d7ae4e2ce1e79cc2c5
XMLHttpRequest cannot load https://agile-citadel-84570.herokuapp.com/login/github?code=13d7ae4e2ce1e79cc2c5. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://opensurvey.herokuapp.com' is therefore not allowed access. The response had HTTP status code 404.

**Comment by tbgse** [comment]
Thanks for reporting, should be fixed now.
