### ISSUE TITLE
Allow users to see all "public" polls.

### ISSUE THREAD

**Issue by AkiraLaine** [tbgse/opensurvey#12]
There could be some kind of option to make a poll "public" so that a user can go to "Home" and see *all* public polls (or something like that).

Private polls would only be accessible through the link.

**Comment by tbgse** [comment]
I'm not sure what would be the value in this, in which usecase would a user want to respond to random surveys in his homescreen?

**Comment by AkiraLaine** [comment]
Well, there is nothing else I can do other than create surveys. I want to be able to see other peoples polls and maybe search through them. 

Of course, I don't want to vote on completely random polls, but it would be nice to have the ability to search for polls and do something else on the app.

Otherwise, what makes OpenSurvey stand out from every other voting app?

**Comment by tbgse** [comment]
It's first and foremost a tool to gather data and evaluate /export results. It's not meant to be entertaining users by browsing through polls etc. but rather aimed at Students writing on dissertations who need to gather data or companies running questionnaires interally with employees or externally with customers.

You'll see after you've created your survey and you browse the first responses (clicking on show responses in the dashboard) that there is quite a few filter options etc. available for diving deeper into the answers of your survey.

What makes OpenSurvey different here is that it's as far as I know of one of the only truly free and open source solutions that can answer all those needs in a straightforward way.
