### ISSUE TITLE
Fonts not being downloaded

### ISSUE THREAD

**Issue by aledpardo** [tbgse/opensurvey#7]
The fonts can't be download by the browser due to an security issue. The Chrome console shows the message:

Mixed Content: The page at 'https://agile-citadel-84570.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,500'. This request has been blocked; the content must be served over HTTPS.

OS: Mac OSx
Browser: Chrome 48.0.2564.103 (64-bit)
URL: https://agile-citadel-84570.herokuapp.com/edit

**Comment by tbgse** [comment]
Thanks for posting this, it's fixed now!
