### ISSUE TITLE
Answers options not being captured correctly

### ISSUE THREAD

**Issue by aledpardo** [tbgse/opensurvey#9]
There are incorrect bindings for the answers for take the survey on https://agile-citadel-84570.herokuapp.com/survey/qVPk1b

Steps to reproduce:
1 - Choose Yes on question 1
2 - Choose No on question 2
Results: The question 2 continues with blank answer and the answer for question 1 changes to No.

**Comment by tbgse** [comment]
Thanks for reporting this, I think I have fixed the problem. 
Please check: https://opensurvey.herokuapp.com/survey/qVPk1b
